from marshmallow import Schema, fields


class BoxscoreSchema(Schema):
    game_id = fields.String(required=True)
    team_id = fields.Integer(required=False)
    team_city = fields.String(required=False)
    team_name = fields.String(required=False)
    team_tricode = fields.String(required=False)
    team_slug = fields.String(required=False)
    player_id = fields.Integer(required=True)
    first_name = fields.String(required=False)
    family_name = fields.String(required=False)
    name_i = fields.String(required=False)
    player_slug = fields.String(required=False)
    position = fields.String(required=False)
    comment = fields.String(required=False)
    jersey_num = fields.Integer(required=False)
    minutes = fields.Float(required=False)
    field_goals_made = fields.Integer(required=False)
    field_goals_attempted = fields.Integer(required=False)
    field_goals_percentage = fields.Float(required=False)
    three_pointers_made = fields.Integer(required=False)
    three_pointers_attempted = fields.Integer(required=False)
    three_pointers_percentage = fields.Float(required=False)
    free_throws_made = fields.Integer(required=False)
    free_throws_attempted = fields.Integer(required=False)
    free_throws_percentage = fields.Float(required=False)
    rebounds_offensive = fields.Integer(required=False)
    rebounds_defensive = fields.Integer(required=False)
    rebounds_total = fields.Integer(required=False)
    assists = fields.Integer(required=False)
    steals = fields.Integer(required=False)
    blocks = fields.Integer(required=False)
    turnovers = fields.Integer(required=False)
    fouls_personal = fields.Integer(required=False)
    points = fields.Integer(required=False)
    plus_minus_points = fields.Float(required=False)